# Generated by Django 2.0.1 on 2018-01-27 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='auditory_name')),
                ('duty', models.TextField(blank=True, verbose_name='auditory_duty')),
                ('knowledge', models.TextField(blank=True, verbose_name='auditory_knowledge')),
                ('demography', models.TextField(blank=True, verbose_name='auditory_demography')),
                ('relations', models.TextField(blank=True, verbose_name='auditory_relations')),
                ('environment', models.TextField(blank=True, verbose_name='auditory_environment')),
                ('resume', models.TextField(blank=True, verbose_name='auditory_resume')),
            ],
            options={
                'verbose_name_plural': 'auditories',
                'verbose_name': 'auditory',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='chapter_name')),
                ('questions', models.TextField(blank=True, verbose_name='questions')),
            ],
            options={
                'verbose_name_plural': 'chapters',
                'verbose_name': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='project_name')),
                ('aim_action', models.TextField(blank=True, verbose_name='aim_action')),
                ('aim_auditory', models.TextField(blank=True, verbose_name='aim_auditory')),
                ('aim_content', models.TextField(blank=True, verbose_name='aim_content')),
                ('reaction_action', models.TextField(blank=True, verbose_name='reaction_action')),
                ('reaction_standart', models.TextField(blank=True, verbose_name='reaction_standart')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('auditory_profiles', models.ManyToManyField(blank=True, to='doc_plan.AuditoryProfile', verbose_name='auditory_profiles')),
                ('chapters', models.ManyToManyField(blank=True, to='doc_plan.Chapter', verbose_name='chapters')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
                'verbose_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question_text')),
                ('question_type', models.CharField(choices=[('a', 'action'), ('k', 'knowledge')], default='a', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'questions',
                'verbose_name': 'question',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='questions',
            field=models.ManyToManyField(blank=True, to='doc_plan.Question', verbose_name='questions'),
        ),
    ]
