# Generated by Django 2.0.1 on 2018-02-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auditory_profiles',
        ),
        migrations.AddField(
            model_name='project',
            name='auditory_profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_plan.AuditoryProfile', verbose_name='auditory_profiles'),
        ),
    ]
