# Generated by Django 2.0.1 on 2018-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0002_auto_20180209_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='auditory_profiles',
            new_name='auditory_profile',
        ),
    ]
