# Generated by Django 2.0.1 on 2018-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0003_auto_20180209_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='questions',
        ),
        migrations.AddField(
            model_name='project',
            name='question_actions',
            field=models.TextField(blank=True, verbose_name='question_actions'),
        ),
        migrations.AddField(
            model_name='project',
            name='question_knowledges',
            field=models.TextField(blank=True, verbose_name='question_knowledges'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
