# Generated by Django 2.0.1 on 2018-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0005_auto_20180213_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='questions',
            field=models.TextField(blank=True, verbose_name='вопросы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_action',
            field=models.TextField(blank=True, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_auditory',
            field=models.TextField(blank=True, verbose_name='аудитория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='aim_content',
            field=models.TextField(blank=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_demography',
            field=models.TextField(blank=True, verbose_name='демография'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_duty',
            field=models.TextField(blank=True, verbose_name='обязанности'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_environment',
            field=models.TextField(blank=True, verbose_name='окружение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_knowledge',
            field=models.TextField(blank=True, verbose_name='знания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_relations',
            field=models.TextField(blank=True, verbose_name='отношения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auditory_resume',
            field=models.TextField(blank=True, verbose_name='выводы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='doc_plan.Chapter', verbose_name='разделы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question_actions',
            field=models.TextField(blank=True, verbose_name='процедуры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='question_knowledges',
            field=models.TextField(blank=True, verbose_name='знания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reaction_action',
            field=models.TextField(blank=True, verbose_name='реакция'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reaction_standart',
            field=models.TextField(blank=True, verbose_name='стандарт'),
        ),
    ]
