# Generated by Django 2.0.1 on 2018-03-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0006_auto_20180312_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_plan.Chapter')),
            ],
            options={
                'verbose_name': 'разделы плана',
                'verbose_name_plural': 'разделы плана',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='doc_plan.Chapter', verbose_name='разделы'),
        ),
        migrations.AddField(
            model_name='chapterorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_plan.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='chapters_order',
            field=models.ManyToManyField(blank=True, related_name='chapters_order', through='doc_plan.ChapterOrder', to='doc_plan.Chapter', verbose_name='разделы'),
        ),
    ]
