# Generated by Django 2.0.1 on 2018-03-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_plan', '0007_auto_20180323_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chapters',
        ),
    ]
